### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by LoadingScreen115** [Scobalula/Cerberus-Repo#18]
```
Failed to load C:\BO3 Mod Tools\Cerberus\scripts\zm\zm_zod_gamemodes.gscc
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at Cerberus.Logic.BlackOps3Script.LoadExports()
   at Cerberus.Logic.ScriptBase..ctor(BinaryReader , Dictionary`2 )
   at Cerberus.Logic.ScriptBase.LoadScript(BinaryReader reader, Dictionary`2 hashTables)
   at Cerberus.UI.MainWindow.LoadScriptFiles(String[] files)
```
Been getting this error when trying to open several different files from many mods/maps from the Workshop. This a known issue?

**Comment by Davidvanzutphen** [comment]
Having the same issue here. My guess is that maybe we have an OS system running that is not standard US. Mine is EU so I had to change windows settings to be able to run ModTools. Would like to know if that might be the case?
